### ISSUE TITLE
wafw00f https://example.org Traceback (most recent call last):   File "/usr/local/bin/wafw00f", line 4, in <module>     __import__('pkg_resources').run_script('wafw00f==2.1.0', 'wafw00f')   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script     self.require(requires)[0].run_script(script_name, ns)   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1453, in run_script     .format(**locals()), pkg_resources.ResolutionError: Script 'scripts/wafw00f' not found in metadata at '/usr/local/lib/python2.7/dist-packages/wafw00f-2.1.0.dist-info'

### ISSUE THREAD

**Issue by Jehad522** [EnableSecurity/wafw00f#105]

**Comment by sandrogauci** [comment]
please open a new issue and follow our instructions [here](https://github.com/EnableSecurity/wafw00f/issues/new?assignees=sandrogauci%2C+0xInfection&labels=&template=bug_report.md&title=)
