### ISSUE TITLE
Error while install wafw00f on Amazon Linux. 

### ISSUE THREAD

**Issue by kluo84** [EnableSecurity/wafw00f#106]
**Describe the bug**
I tried to install wafw00f on Amazon Linux (RHEL) version, I got the error below. I use pip install Sphinx even yum install the Sphinx manually, but it still failed.

Please advise. Thanks
```
zip_safe flag not set; analyzing archive contents...
wafw00f.manager: module references __file__
Traceback (most recent call last):
  File "./setup.py", line 53, in <module>
    'Sphinx',
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
EOFError: EOF read where object expected
```

**Comment by sandrogauci** [comment]
The issue does not seem to have anything to do with wafw00f (or Sphinx) but rather with setuptools.

Delete your wafw00f directory, and either use `pip install wafw00f` or run `python setup.py install` again. If it happens again, please try to reproduce the issue on other systems (e.g. Kali or a normal Fedora/Ubuntu) and reopen the issue if you do.
