### ISSUE TITLE
刚开始运行正常也可以查询,然后python install steup.py就提示以下

### ISSUE THREAD

**Issue by liutuo008** [EnableSecurity/wafw00f#120]
Traceback (most recent call last):
  File "/usr/local/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==2.1.0', 'wafw00f')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 739, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1486, in run_script
pkg_resources.ResolutionError: No script named 'wafw00f'

**Comment by 0xInfection** [comment]
Please use the issue template for pulling up new issues. Some info about the system (e.g. OS and platform) is required for troubleshooting issues.
