### ISSUE TITLE
ImportError: No module named pluginbase

### ISSUE THREAD

**Issue by snifuh** [EnableSecurity/wafw00f#137]
here is my problem:
wafw00f
Traceback (most recent call last):
  File "/usr/local/bin/wafw00f", line 4, in <module>
    from wafw00f import main
  File "/usr/local/lib/python2.7/dist-packages/wafw00f/main.py", line 22, in <module>
    from wafw00f.manager import load_plugins
  File "/usr/local/lib/python2.7/dist-packages/wafw00f/manager.py", line 9, in <module>
    from pluginbase import PluginBase
ImportError: No module named pluginbase

when i first used it it worked fine, now it just says this, any suggestions?

**Comment by user12243** [comment]
Try reinstalling

**Comment by 0xInfection** [comment]
Please make an effort of reading the readme at least before installing/using any tool.

**Comment by snifuh** [comment]
> Try reinstalling

I tried, and i even tried downloading the zip file but it just didnt work
