### ISSUE TITLE
error [AttributeError: 'NoneType' object has no attribute 'status_code']

### ISSUE THREAD

**Issue by foozzi** [EnableSecurity/wafw00f#146]
**Describe the bug**
see debug output

**To Reproduce**
`wafw00f 7money.com`

**Desktop (please complete the following information):**
 - OS: Linux
 - OS version, distribution: Arch Linux
 - Python version: 3.9.7

**Debug output**
```
[*] Checking https://7money.com
ERROR:wafw00f:Something went wrong ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[+] Generic Detection results:
ERROR:wafw00f:Something went wrong ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/home/user/.local/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==2.1.0', 'wafw00f')
  File "/home/user/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/.local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/user/.local/lib/python3.9/site-packages/wafw00f-2.1.0-py3.9.egg/EGG-INFO/scripts/wafw00f", line 8, in <module>
    main.main()
  File "/home/user/.local/lib/python3.9/site-packages/wafw00f-2.1.0-py3.9.egg/wafw00f/main.py", line 450, in main
    if attacker.genericdetect():
  File "/home/user/.local/lib/python3.9/site-packages/wafw00f-2.1.0-py3.9.egg/wafw00f/main.py", line 95, in genericdetect
    if resp1.status_code != resp3.status_code:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

resp3 is None

**Comment by 0xInfection** [comment]
Thanks for opening the issue @foozzi, I've address the issue in MR #149. Please test out the branch and lmk if it is working!

**Comment by foozzi** [comment]
@0xInfection fixed, thanks
