### ISSUE TITLE
DistributionNotFound while trying to run the tool

### ISSUE THREAD

**Issue by hexclann** [EnableSecurity/wafw00f#151]
**Describe the bug**
```
Traceback (most recent call last):
  File "/usr/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==2.1.0', 'wafw00f')
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3266, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wafw00f==2.1.0' distribution was not found and is required by the application
```

**To Reproduce**
wafw00f

**Expected behavior**
Program should run

**Desktop (please complete the following information):**
 - OS: Linux
 - OS version, distribution: Debian 10 amd64
 - Python version: python 3.7

**Debug output**
Same error

**Comment by 0xInfection** [comment]
How did you install wafw00f?

**Comment by hexclann** [comment]
I cloned the repo and ran `python3 setup.py install`

**Comment by 0xInfection** [comment]
I just setup a new Debian 10 VM running Python 3.7.3, and installed wafw00f. Everything seems to be fine and I couldn't reproduce your issue, Googling around the error points me to upgrade the pip version. Can you run the following command, and try installing wafw00f again?
```
sudo python3 -m pip install --upgrade pip
```

**Comment by sandrogauci** [comment]
closing for now
