### ISSUE TITLE
idna does work failed

### ISSUE THREAD

**Issue by blackcodersec** [EnableSecurity/wafw00f#201]
My command is `wafw00f -i domains.txt -o output.csv -f csv`

```
Traceback (most recent call last):
  File "/home/lol/.local/bin/wafw00f", line 8, in <module>
    main.main()
  File "/home/lol/.local/lib/python3.10/site-packages/wafw00f/main.py", line 480, in main
    attacker = WAFW00F(target, debuglevel=options.verbose, path=path,
  File "/home/lol/.local/lib/python3.10/site-packages/wafw00f/main.py", line 44, in __init__
    self.rq = self.normalRequest()
  File "/home/lol/.local/lib/python3.10/site-packages/wafw00f/main.py", line 47, in normalRequest
    return self.Request()
  File "/home/lol/.local/lib/python3.10/site-packages/wafw00f/lib/evillib.py", line 77, in Request
    req = requests.get(self.target, proxies=self.proxies, headers=h, timeout=timeout,
  File "/home/lol/.local/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/lol/.local/lib/python3.10/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lol/.local/lib/python3.10/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lol/.local/lib/python3.10/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/lol/.local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/lol/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/lol/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/lol/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/lol/.local/lib/python3.10/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/lol/.local/lib/python3.10/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/lol/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

**Comment by 0xInfection** [comment]
python3.10 is a bit broken for a lot of libraries. I would suggest you to try python 3.9 and see if this error exists. Feel free to reopen this issue if you can replicate this error on 3.9 as well.
