### ISSUE TITLE
Wafw00f fails when trying to detect against https via a http proxy.

### ISSUE THREAD

**Issue by mnowrot** [EnableSecurity/wafw00f#28]
```
$ wafw00f --proxy=http://127.0.0.1:8080 https://google.com

                                 ^     ^
        _   __  _   ____ _   __  _    _   ____
       ///7/ /.' \ / __////7/ /,' \ ,' \ / __/
      | V V // o // _/ | V V // 0 // 0 // _/
      |_n_,'/_n_//_/   |_n_,' \_,' \_,'/_/
                                <
                                 ...'

    WAFW00F - Web Application Firewall Detection Tool

    By Sandro Gauci && Wendel G. Henrique

Checking https://google.com
Traceback (most recent call last):
  File "/usr/local/bin/wafw00f", line 8, in <module>
    main.main()
  File "/usr/local/lib/python2.7/site-packages/wafw00f/main.py", line 419, in main
    if attacker.normalrequest() is None:
  File "/usr/local/lib/python2.7/site-packages/wafw00f/main.py", line 96, in normalrequest
    return self.request(usecache=usecache, cacheresponse=cacheresponse, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/wafw00f/lib/evillib.py", line 320, in request
    r = self._request(method, path, headers)
  File "/usr/local/lib/python2.7/site-packages/wafw00f/lib/evillib.py", line 362, in _request
    h = conn_factory(connect_host, connect_port,**params)
TypeError: __init__() got an unexpected keyword argument 'context'
```

**Comment by sandrogauci** [comment]
Thanks for reporting that @mnowrot .. let me get that fixed.

**Comment by sandrogauci** [comment]
can you check the latest commit? 2ca7a4a3697928edb088679b655ba4c6a70b8a8c
The exception is now fixed but support for HTTPS URLs over HTTP proxies is not implemented. I've been looking for a clean way to implement this but did not find any good examples showing how to use [`set_tunnel`](https://docs.python.org/2/library/httplib.html#httplib.HTTPConnection.set_tunnel) properly. You're welcome to submit a fix of course ;-)
