### ISSUE TITLE
Latest version of html5lib breaks wafw00f

### ISSUE THREAD

**Issue by gtech** [EnableSecurity/wafw00f#37]
$wafw00f

Traceback (most recent call last):
  File "/usr/local/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==0.9.4', 'wafw00f')
  File "/home/<user>/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/<user>/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/wafw00f-0.9.4-py2.7.egg/EGG-INFO/scripts/wafw00f", line 4, in <module>
    from wafw00f import main
  File "/usr/local/lib/python2.7/dist-packages/wafw00f-0.9.4-py2.7.egg/wafw00f/main.py", line 53, in <module>
    from wafw00f.lib.evillib import oururlparse, scrambledheader, waftoolsengine
  File "/usr/local/lib/python2.7/dist-packages/wafw00f-0.9.4-py2.7.egg/wafw00f/lib/evillib.py", line 14, in <module>
    from bs4 import BeautifulSoup
  File "build/bdist.linux-x86_64/egg/bs4/__init__.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/__init__.py", line 314, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/_html5lib.py", line 70, in <module>
AttributeError: 'module' object has no attribute '_base'

------------------------------------------------------------------------------------------

Rolling back the version of html5lib is a functioning workaround:

pip install --upgrade html5lib==1.0b8

**Comment by kkirsche** [comment]
Latest version in pip still shows this error for me at least. Not sure if the goal is to update the pip package once more items are put in the next update.

**Comment by akun** [comment]
@sandrogauci need release  v0.9.5？

then I will update new version in PyPI

**Comment by sandrogauci** [comment]
@kkirsche please test using the version from the repo. 

@akun will release sometime soon yes. I can add a new simple check #39 to that release other than this fix.
