### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Joestein1** [EnableSecurity/wafw00f#56]
After trying to install i got this error        C:\wafw00f-master>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to wafw00f.egg-info\requires.txt
writing wafw00f.egg-info\PKG-INFO
writing top-level names to wafw00f.egg-info\top_level.txt
writing dependency_links to wafw00f.egg-info\dependency_links.txt
reading manifest file 'wafw00f.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wafw00f.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
copying wafw00f.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying wafw00f.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying wafw00f.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying wafw00f.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying wafw00f.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\wafw00f-0.9.6-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    test_suite='nose.collector',
  File "C:\Python27\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 234, in run
    dry_run=self.dry_run, mode=self.gen_header())
  File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 497, in make_zipfile
    visit(z, dirname, files)
  File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 490, in visit
    z.write(path, p)
  File "C:\Python27\lib\zipfile.py", line 1125, in write
    mtime = time.localtime(st.st_mtime)
ValueError: (22, 'Invalid argument')

Any idea how it could be fixed? 

OS:Win10

**Comment by sandrogauci** [comment]
I'm sorry I couldn't reproduce this issue on my test win10/python2.7. The stack trace indicates that something went wrong with the setuptools / `zipfile.py`.
